### ISSUE TITLE
MagicError: "Invalid magic value in superblock: 0xF2EE (expected 0xEF53)", when unpacking level 2 of Android 7 image file for RK3399

### ISSUE THREAD

**Issue by cdarau** [althafvly/AmlogicKitchen#15]
I'm receiving the underlying error when attempting to unpack level 2 of [this](http://theminixforum.com:9009/firmwares/X39-V004-Android_7.1.2-20201125.7z) Android 7.1.2 image for RK3399 (Minix X39):

```
cdarau@DESKTOP-VT529K8:~/GitHub/AmlogicKitchen$ ./rkunpack.sh
[sudo] password for cdarau:
.....................
Rockchip Kitchen
.....................
.....................
Select level 1,2,3 or q/Q to exit:
1
Deleting existing level1
.....................
Rockchip Kitchen
.....................
Files in input dir (*.img)
1 - x35
2 - x39
.....................
Enter a file name :
x39
********rkImageMaker ver 2.0********
Unpacking image, please wait...
Exporting boot.bin
Exporting firmware.img
Unpacking image success.
Android Firmware Package Tool v2.0
Check file... OK
------- UNPACK ------
package-file    offset=0x800    size=0x2C2
Image/MiniLoaderAll.bin offset=0x1000   size=0x4794E
Image/parameter.txt     offset=0x49000  size=0x38F
Image/trust.img offset=0x49800  size=0x400000
Image/uboot.img offset=0x44A000 size=0x400000
Image/misc.img  offset=0x84A800 size=0xC000
Image/resource.img      offset=0x857000 size=0x817600
Image/kernel.img        offset=0x106E800        size=0x12A8014
Image/boot.img  offset=0x2317000        size=0x18AFFC
Image/recovery.img      offset=0x24A2000        size=0x783190
Image/system.img        offset=0x2C25800        size=0x8C51D0C8
update-script   offset=0x8F143000       size=0x3A5
recover-script  offset=0x8F143800       size=0x10A
Unpack firmware OK!
------ OK ------
Done.
.....................
Rockchip Kitchen
.....................
.....................
Select level 1,2,3 or q/Q to exit:
2
Deleting existing level2
Extracting system
.....Extraction from system.img to system
Traceback (most recent call last):
  File "/home/cdarau/GitHub/AmlogicKitchen/bin/common/imgextractor.py", line 795, in <module>
    Extractor().main(
  File "/home/cdarau/GitHub/AmlogicKitchen/bin/common/imgextractor.py", line 788, in main
    self.__ext4extractor()
  File "/home/cdarau/GitHub/AmlogicKitchen/bin/common/imgextractor.py", line 589, in __ext4extractor
    root = ext4.Volume(file).root
  File "/home/cdarau/GitHub/AmlogicKitchen/bin/common/ext4.py", line 483, in __init__
    raise MagicError("Invalid magic value in superblock: 0x{magic:04X} (expected 0xEF53)".format(
ext4.MagicError: Invalid magic value in superblock: 0xF2EE (expected 0xEF53)
Done.
.....................
Rockchip Kitchen
.....................
.....................
Select level 1,2,3 or q/Q to exit:
```

I'm using the latest version of the code (commit b75430d)

**Comment by althafvly** [comment]
@cdarau  Fixed. Update the tool and try again.
